/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgData;

import java.util.ListIterator;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author User
 */
public class CustomerUI extends javax.swing.JFrame {

    Customertb customers;
    ListIterator <Customertb> iterator;
    
    
    public CustomerUI() {
        initComponents();
        setLocationRelativeTo(rootPane);
        iterator = customertbList.listIterator(0);
    }
    
    //Instantiating object
    Text obj= new Text();
    
    public Customertb getCustomers()
    {
        return customers;
    }
    
    public void setCustomers(Customertb customers)
    {
        Customertb oldCustomers = this.customers;
        this.customers= customers;
        firePropertyChange("customers",oldCustomers,customers);
    }
    
    //Clears the text in text fields
    public void clearFields()
    {
        txfID.setText("");
        txfFirstname.setText("");
        txfLastname.setText("");
        txfPhoneNum.setText("");
        txfAddress.setText("");
    }
    // Inserts Customer information into database
    public void InsertCus()
    {
       //Customertb object
        Customertb cst= new Customertb(); 
        
        //Obtains values from text fields
        cst.setCustomerid((Integer.parseInt(txfID.getText())));
        cst.setFirstname(txfFirstname.getText());
        cst.setLastname(txfLastname.getText());
        cst.setPhonenumber(txfPhoneNum.getText());
        cst.setAddress(txfAddress.getText());
        
        //Connects to database
        RestaurantDBPUEntityManager.getTransaction().begin();
        RestaurantDBPUEntityManager.persist(cst);
        RestaurantDBPUEntityManager.getTransaction().commit();
        
        //Adds values into database
        customertbList.clear();
        customertbList.addAll(customertbQuery.getResultList());
        iterator = customertbList.listIterator(0);
           
        //Clears text fields and displays message
        clearFields();
        JOptionPane.showMessageDialog(null,"Insert Completed");
    }
    
    public void InsertAct()
    {
        //Values
        String ID= txfID.getText();
        String Name= txfFirstname.getText();
        String Surname= txfLastname.getText();
        String PhoneNum= txfPhoneNum.getText();

        //Checks if fields are appropriately filled
        if(obj.CheckNum(ID)==true && obj.CheckString(Name)==true && obj.CheckString(Surname)==true && obj.CheckPhone(PhoneNum)==true)
        {
            InsertCus();
        }
    }
    //Updates Customer information into database
    public void Update()
    {
        // Selected row displayed in text fields for editing
        int i=tblCustomer.getSelectedRow();
        TableModel model =(TableModel)tblCustomer.getModel();
        if(i >=0)
        {
            //Obtains values from text fields
            model.setValueAt(txfID.getText(),i,0);
            model.setValueAt(txfFirstname.getText(),i,1);
            model.setValueAt(txfLastname.getText(),i,2);
            model.setValueAt(txfPhoneNum.getText(),i,3);
            model.setValueAt(txfAddress.getText(),i,4);
            
            //Connects to database and updates it
            RestaurantDBPUEntityManager.getTransaction().begin();
            RestaurantDBPUEntityManager.getTransaction().commit();
            RestaurantDBPUEntityManager.clear(); 
            JOptionPane.showMessageDialog(null, "Update Complete");
        }
         
        //Displays message to inform that a customer must be selected
        else{
            JOptionPane.showMessageDialog(null, "Please click on a customer in the table");
        }
    }
    
    public void MouseClick()
    {
        //Allows data to be displayed in text field when table is clicked
        int i = tblCustomer.getSelectedRow();
        TableModel model =tblCustomer.getModel();
        
        //Inserts values into text fields
        txfID.setText(model.getValueAt(i,0).toString());
        txfFirstname.setText(model.getValueAt(i,1).toString());
        txfLastname.setText(model.getValueAt(i,2).toString());
        txfPhoneNum.setText(model.getValueAt(i,3).toString());
        txfAddress.setText(model.getValueAt(i,4).toString());
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        RestaurantDBPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("RestaurantDBPU").createEntityManager();
        customertbQuery = java.beans.Beans.isDesignTime() ? null : RestaurantDBPUEntityManager.createQuery("SELECT c FROM Customertb c");
        customertbList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : customertbQuery.getResultList();
        btnHelp = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        lblFirstname = new javax.swing.JLabel();
        lblLastname = new javax.swing.JLabel();
        lblPhoneNum = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        txfID = new javax.swing.JTextField();
        txfFirstname = new javax.swing.JTextField();
        txfLastname = new javax.swing.JTextField();
        txfPhoneNum = new javax.swing.JTextField();
        txfAddress = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        lblPic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(895, 575));
        getContentPane().setLayout(null);

        btnHelp.setText("Help");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        btnHelp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnHelpKeyPressed(evt);
            }
        });
        getContentPane().add(btnHelp);
        btnHelp.setBounds(14, 13, 59, 27);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(30, 460, 100, 40);

        lblID.setForeground(new java.awt.Color(255, 255, 255));
        lblID.setText("CustomerID");
        getContentPane().add(lblID);
        lblID.setBounds(190, 210, 80, 30);

        lblFirstname.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstname.setText("Firstname");
        getContentPane().add(lblFirstname);
        lblFirstname.setBounds(190, 250, 80, 40);

        lblLastname.setForeground(new java.awt.Color(255, 255, 255));
        lblLastname.setText("Lastname");
        getContentPane().add(lblLastname);
        lblLastname.setBounds(190, 300, 80, 30);

        lblPhoneNum.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoneNum.setText("Phone Number");
        getContentPane().add(lblPhoneNum);
        lblPhoneNum.setBounds(190, 340, 90, 40);

        lblAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress.setText("Address");
        getContentPane().add(lblAddress);
        lblAddress.setBounds(190, 390, 80, 40);
        getContentPane().add(txfID);
        txfID.setBounds(290, 205, 180, 30);
        getContentPane().add(txfFirstname);
        txfFirstname.setBounds(290, 250, 180, 30);
        getContentPane().add(txfLastname);
        txfLastname.setBounds(290, 300, 180, 30);
        getContentPane().add(txfPhoneNum);
        txfPhoneNum.setBounds(290, 350, 180, 30);
        getContentPane().add(txfAddress);
        txfAddress.setBounds(290, 400, 180, 30);

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert);
        btnInsert.setBounds(580, 220, 100, 60);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(580, 340, 100, 60);

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext);
        btnNext.setBounds(750, 460, 100, 40);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, customertbList, tblCustomer);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${customerid}"));
        columnBinding.setColumnName("Customerid");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${firstname}"));
        columnBinding.setColumnName("Firstname");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${lastname}"));
        columnBinding.setColumnName("Lastname");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${phonenumber}"));
        columnBinding.setColumnName("Phonenumber");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${address}"));
        columnBinding.setColumnName("Address");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        tblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCustomer);
        if (tblCustomer.getColumnModel().getColumnCount() > 0) {
            tblCustomer.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 40, 720, 160);

        lblPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgData/Restaurant.PNG"))); // NOI18N
        lblPic.setText("Insert");
        getContentPane().add(lblPic);
        lblPic.setBounds(0, 0, 880, 530);

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Goes to Main Screen
        MainScreen main=new MainScreen();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // Goes to Customer2UI
        Customer2UI customer=new Customer2UI();
        customer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        InsertAct();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        // Message describing the function of other buttons
        JOptionPane.showMessageDialog
        (null,obj.Help3());
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnHelpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnHelpKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHelpKeyPressed

    private void tblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerMouseClicked
        //Displays values in Text fields
        MouseClick();
    }//GEN-LAST:event_tblCustomerMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        //Updates Fields
        Update();
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager RestaurantDBPUEntityManager;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnUpdate;
    private java.util.List<pkgData.Customertb> customertbList;
    private javax.persistence.Query customertbQuery;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblPhoneNum;
    private javax.swing.JLabel lblPic;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTextField txfAddress;
    private javax.swing.JTextField txfFirstname;
    private javax.swing.JTextField txfID;
    private javax.swing.JTextField txfLastname;
    private javax.swing.JTextField txfPhoneNum;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
